version: "3.3"

services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile-production
            args:
                http_proxy: ${npm_config_proxy}

volumes:
    nodemodules: {}
